const staff = [
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
];

export default staff;
