interface IStaff {
  id: number,
  firstName: string,
  lastName: string,
  patronymic: string,
  email: string,
  appounted: number,
  passed: number,
  raiting: number,
  department: string,
}

const staff: IStaff[] = [
  {
    id: 1,
    firstName: 'Самый',
    lastName: 'Первый',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 2,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 3,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 4,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 5,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 6,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 7,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 8,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 9,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 10,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 11,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 12,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 13,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 14,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 15,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 16,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 17,
    firstName: 'Самый',
    lastName: 'Последний',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
];

export default staff;
