const staff = [
  {
    id: 1,
    firstname: 'Самый',
    surname: 'Первый',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 2,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 3,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 4,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 5,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Маркетинг',
  },
  {
    id: 6,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 7,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 8,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Финансовый отдел',
  },
  {
    id: 9,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 10,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 11,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 12,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'Отдел продаж',
  },
  {
    id: 13,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 14,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 15,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 16,
    firstname: 'Иван',
    surname: 'Иванов',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
  {
    id: 17,
    firstname: 'Самый',
    surname: 'Последний',
    patronymic: 'Иванович',
    email: 'ivan.ivanov@company.com',
    appounted: 21,
    passed: 21,
    raiting: 21,
    department: 'HR',
  },
];

export default staff;
